<a href="https://colab.research.google.com/github/Preet28/Fake-Review-Detection/blob/main/Copy_of_ClassifierAlgo_bigrams_count_vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/Preet28/Fake-Review-Detection.git

Cloning into 'Fake-Review-Detection'...
remote: Enumerating objects: 49, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 49 (delta 23), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (49/49), 921.31 KiB | 2.92 MiB/s, done.
Resolving deltas: 100% (23/23), done.


In [ ]:
 import pandas as pd
 import numpy as np
 import re

In [ ]:
df = pd.read_csv('/content/Fake-Review-Detection/deceptive-opinion.csv')
df.head(4)

deceptive   hotel  polarity       source  \
0  truthful  conrad  positive  TripAdvisor   
1  truthful   hyatt  positive  TripAdvisor   
2  truthful   hyatt  positive  TripAdvisor   
3  truthful    omni  positive  TripAdvisor   

                                                text  
0  We stayed for a one night getaway with family ...  
1  Triple A rate with upgrade to view room was le...  
2  This comes a little late as I'm finally catchi...  
3  The Omni Chicago really delivers on all fronts...

In [ ]:
df = df.drop(['hotel','polarity','source'], axis = 1)
df.head(2)

deceptive                                               text
0  truthful  We stayed for a one night getaway with family ...
1  truthful  Triple A rate with upgrade to view room was le...

In [ ]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

stopwords = set(stopwords.words('english'))

def clean_text(text):

    text = re.sub('[^\w\s]', '', text)
    text = text.lower()
    text = ' '.join([word for word in text.split() if word not in stopwords])
    return text

df['text'] = df['text'].apply(clean_text)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
df.text.tail(3)

1597    intercontinental chicago magnificent mile outs...
1598    palmer house hilton looks good pictures outsid...
1599    former chicagoan im appalled amalfi hotel chic...
Name: text, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
# Splitting the data into features and labels
X = df['text']
y = df['deceptive']

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
vectorizer = CountVectorizer(ngram_range = (2,2))
X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
classifiers = {
    'Logistic Regression' : LogisticRegression(),
    'Naive Bayes': MultinomialNB(),
    'k-Nearest Neighbors (k=5)': KNeighborsClassifier(n_neighbors=5),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Support Vector Machine': SVC()
}

# Train and evaluate each classifier
for name, classifier in classifiers.items():
    print(f"Classifier: {name}")
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    accuracy = classifier.score(X_test, y_test)
    print("Accuracy:", accuracy)
    conf_matrix = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix \n",conf_matrix)
    report = classification_report(y_test, y_pred)
    print("Classification Report:\n", report)
    print("*" * 50)

Classifier: Logistic Regression
Accuracy: 0.79375
Confusion Matrix 
 [[131  21]
 [ 45 123]]
Classification Report:
               precision    recall  f1-score   support

   deceptive       0.74      0.86      0.80       152
    truthful       0.85      0.73      0.79       168

    accuracy                           0.79       320
   macro avg       0.80      0.80      0.79       320
weighted avg       0.80      0.79      0.79       320

**************************************************
Classifier: Naive Bayes
Accuracy: 0.81875
Confusion Matrix 
 [[144   8]
 [ 50 118]]
Classification Report:
               precision    recall  f1-score   support

   deceptive       0.74      0.95      0.83       152
    truthful       0.94      0.70      0.80       168

    accuracy                           0.82       320
   macro avg       0.84      0.82      0.82       320
weighted avg       0.84      0.82      0.82       320

**************************************************
Classifier: k-Neares

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy: 0.74375
Confusion Matrix 
 [[109  43]
 [ 39 129]]
Classification Report:
               precision    recall  f1-score   support

   deceptive       0.74      0.72      0.73       152
    truthful       0.75      0.77      0.76       168

    accuracy                           0.74       320
   macro avg       0.74      0.74      0.74       320
weighted avg       0.74      0.74      0.74       320

**************************************************
Classifier: Random Forest
Accuracy: 0.76875
Confusion Matrix 
 [[ 97  55]
 [ 19 149]]
Classification Report:
               precision    recall  f1-score   support

   deceptive       0.84      0.64      0.72       152
    truthful       0.73      0.89      0.80       168

    accuracy                           0.77       320
   macro avg       0.78      0.76      0.76       320
weighted avg       0.78      0.77      0.76       320

**************************************************
Classifier: Support Vector Machine
Accuracy: 0.715